Feat: Using Redis to fetch all Customers
Winderson/tech-challenge pull request #45
Opened 2024-12-01 19:03 UTC by amanda-maschio

- Implementation of `CacheService`, which encapsulates Redis to speed up the retrieval of `Customers`
- Implementation of endpoint to update a `Product Category`

2024-12-01 22:32 UTC, LucasAccurcio requested changes

2024-12-01 22:32 UTC, LucasAccurcio commented on src/core/application/services/cacheService.ts
> +import redisClient from '../ports/output/redisClient';
Não seria bom utilizar aqui o pathResolution? (@src/@src/core/application/ports/output/...)

2024-12-01 22:32 UTC, LucasAccurcio commented on src/core/application/services/productCategoryService.ts
> +import { DeleteProductCategoryParams, UpdateProductCategoryParams } from '../ports/input/productCategory';
Aqui acredito que tb caberia a utilização do pathResolution para as linha 5 e 6:
- '@exceptions/invalidProductCategoryException'
- '@ports/input/productCategory'

2024-12-01 22:32 UTC, LucasAccurcio commented on src/core/application/ports/output/redisClient.ts
Fiquei na duvida do local correto desse arquivo, ao olhar para ele, fiquei com a impressão que ele deveria seguir a mesma regra do PrismaClient em '/src/adapter/driven/infra/lib', o que acha?

2024-12-02 13:19 UTC, amanda-maschio commented on src/core/application/ports/output/redisClient.ts
Verdade, acredito que seja melhor sim, movido para `/src/adapter/driven/infra/lib`

2024-12-03 22:19 UTC, LucasAccurcio approved these changes

2024-12-03 23:40 UTC, merged